[package]
name = "auv-cli-invoke"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
readme.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
default = ["overlay"]
overlay = ["auv-driver/overlay"]

[dependencies]
auv = { path = "../auv" }
auv-api-proto = { path = "../auv-api-proto" }
auv-cli-common = { path = "../auv-cli-common" }
auv-cli-invoke-macros = { path = "../auv-cli-invoke-macros" }
auv-driver = { path = "../auv-driver" }
auv-media-macos = { path = "../auv-media-macos" }
auv-scan = { path = "../auv-scan" }
auv-tracing = { path = "../auv-tracing" }
anstream = "1"
anstyle = "1"
clap = { version = "4.5", features = ["derive"] }
comfy-table = { version = "7", default-features = false }
futures-executor = "0.3"
futures-util = { version = "0.3", features = ["io"] }
image = { version = "0.25", default-features = false, features = ["png"] }
prost-types = "0.14"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "time"] }
tokio-util = { version = "0.7", features = ["rt"] }
thiserror = "2"

[dev-dependencies]
auv-tracing = { path = "../auv-tracing", features = ["memory-store"] }
tokio = { version = "1", features = ["macros", "rt"] }

[target.'cfg(target_os = "macos")'.dependencies]
auv-driver-macos = { path = "../auv-driver-macos" }
