// File: src/driver/macos/descriptor.rs
use super::*;

pub(crate) fn driver_descriptor() -> DriverDescriptor {
  DriverDescriptor {
    id: "macos.desktop",
    summary: "macOS desktop primitives for capture, OCR, window resolution, AX tree inspection, and input control.",
    capabilities: &[
      "desktop.capture-display",
      "desktop.capture-region",
      "desktop.capture-window",
      "desktop.list-displays",
      "desktop.list-windows",
      "desktop.capture-ax-tree",
      "desktop.probe-permissions",
      "desktop.identify-point",
      "desktop.project-screenshot-point",
      "desktop.probe-coordinate-readiness",
      "desktop.find-screen-text",
      "desktop.wait-screen-text",
      "desktop.find-screen-rows",
      "desktop.wait-screen-rows",
      "desktop.find-window-text",
      "desktop.wait-window-text",
      "desktop.find-window-rows",
      "desktop.wait-window-rows",
      "desktop.find-image-text",
      "desktop.verify-ax-text",
      "control.activate-app",
      "control.focus-text-input",
      "control.press-button",
      "control.type-text",
      "control.paste-text-preserve-clipboard",
      "control.press-key",
      "control.click-point",
      "control.click-window-point",
      "control.click-screen-text",
      "control.click-screen-row",
      "control.click-window-text",
      "control.click-window-row",
      "control.scroll-point",
    ],
    donor_boundary: "Borrow host desktop primitives from platform APIs, but keep MCP tools, action executors, approval queues, and workflow shells out of AUV core.",
  }
}
