apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: osworld-kvm
spec:
  rules:
    - name: KVM is enabled
      labels:
        feature.node.kubernetes.io/kvm: "true"
      matchFeatures:
        - feature: kernel.kvm
          matchExpressions:
            enabled:
              op: IsTrue
