[package]
name = "auv-apple-music"
version.workspace = true
edition.workspace = true
publish.workspace = true
readme.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "auv-apple-music"
path = "src/bin/auv-apple-music.rs"

[features]
default = []
tracing = ["dep:auv-tracing", "dep:image"]

[dependencies]
auv-driver = { path = "../../../crates/auv-driver" }
auv-tracing = { path = "../../../crates/auv-tracing", optional = true }
clap = { version = "4.5", features = ["derive"] }
image = { version = "0.25", default-features = false, features = ["png"], optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[target.'cfg(target_os = "windows")'.dependencies]
auv-driver-windows = { path = "../../../crates/auv-driver-windows" }

[target.'cfg(target_os = "macos")'.dependencies]
auv-driver-macos = { path = "../../../crates/auv-driver-macos" }
