/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Install and register the signed AUV Helper embedded in this build, or
 * `helperApp` when the embedding application ships its own helper.
 *
 * The work runs off the JavaScript thread because archive verification and
 * ServiceManagement registration perform blocking platform calls.
 */
export declare function installMacosHelper(options?: MacosHelperOptions | undefined | null): Promise<MacosHelperStatus>

/** Which helper app setup manages. */
export interface MacosHelperOptions {
  /**
   * Absolute path of the unpacked, signed helper app shipped by the
   * application embedding AUV. Omit it to manage the official AUV Helper
   * embedded in release builds. Pass the same path to `startAuv({ platforms:
   * { macos: { helperApp } } })` so the daemon trusts that helper.
   */
  helperApp?: string
}

/**
 * Inspect the AUV Helper installation used for locked macOS sessions.
 *
 * Signature validation and ServiceManagement inspection run off the
 * JavaScript thread because they perform blocking platform calls.
 */
export declare function macosHelperStatus(options?: MacosHelperOptions | undefined | null): Promise<MacosHelperStatus>

export interface MacosHelperStatus {
  state: string
  detail?: string
  /**
   * Whether this binding can install a helper: one embedded by a release
   * build, or `helperApp`.
   */
  helperEmbedded: boolean
}

/**
 * Return the version embedded into the native binding.
 *
 * The JavaScript entrypoint compares this value with its package manifest so
 * a partially published release fails before it starts an AUV sidecar.
 */
export declare function nativePackageVersion(): string

/** Open System Settings at Privacy & Security > Accessibility. */
export declare function openMacosHelperAccessibilitySettings(): void

/** Open System Settings at General > Login Items & Extensions. */
export declare function openMacosHelperBackgroundItemsSettings(options?: MacosHelperOptions | undefined | null): void

/**
 * Unregister the helper, reset its Accessibility decision, and remove its app.
 *
 * Enrollment remains in the current user's login Keychain. The work runs off
 * the JavaScript thread because it waits for ServiceManagement termination and
 * performs filesystem and TCC operations.
 */
export declare function uninstallMacosHelper(options?: MacosHelperOptions | undefined | null): Promise<MacosHelperStatus>
