/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Return the version embedded into the native binding.
 *
 * The JavaScript entrypoint compares this value with its package manifest so
 * a partially published release fails before it starts an AUV sidecar.
 */
export declare function nativePackageVersion(): string
