/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Install and register the signed AUV Helper embedded in this build.
 *
 * The work runs off the JavaScript thread because archive verification and
 * ServiceManagement registration perform blocking platform calls.
 */
export declare function installMacosHelper(): Promise<MacosHelperStatus>

/**
 * Inspect the AUV Helper installation used for locked macOS sessions.
 *
 * Signature validation and ServiceManagement inspection run off the
 * JavaScript thread because they perform blocking platform calls.
 */
export declare function macosHelperStatus(): Promise<MacosHelperStatus>

export interface MacosHelperStatus {
  state: string
  detail?: string
  helperEmbedded: boolean
}

/**
 * Return the version embedded into the native binding.
 *
 * The JavaScript entrypoint compares this value with its package manifest so
 * a partially published release fails before it starts an AUV sidecar.
 */
export declare function nativePackageVersion(): string

/** Open System Settings at Privacy & Security > Accessibility. */
export declare function openMacosHelperAccessibilitySettings(): void

/** Open System Settings at General > Login Items & Extensions. */
export declare function openMacosHelperBackgroundItemsSettings(): void

/**
 * Unregister the helper, reset its Accessibility decision, and remove its app.
 *
 * Enrollment remains in the current user's login Keychain. The work runs off
 * the JavaScript thread because it waits for ServiceManagement termination and
 * performs filesystem and TCC operations.
 */
export declare function uninstallMacosHelper(): Promise<MacosHelperStatus>
