// File: src/driver/macos/support/mod.rs
mod artifacts;
mod ax;
mod call;
mod display;
mod geometry;
mod observation;
mod ocr;
mod ocr_commands;
mod overlay_evidence;
mod parse;
mod recognition;
mod runtime;
mod scripts;
mod selector;
pub(crate) mod template_match;

pub(crate) use self::artifacts::*;
pub(crate) use self::ax::*;
pub(crate) use self::call::*;
pub(crate) use self::display::*;
pub(crate) use self::geometry::*;
pub(crate) use self::observation::*;
pub(crate) use self::ocr::*;
pub(crate) use self::ocr_commands::*;
pub(crate) use self::overlay_evidence::*;
pub(crate) use self::parse::*;
pub(crate) use self::recognition::*;
pub(crate) use self::runtime::*;
pub(crate) use self::scripts::*;
pub(crate) use self::selector::*;
