[package]
name = "auv-driver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = true
readme.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
default = []
overlay = ["dep:auv-driver-overlay", "auv-driver-linux/overlay", "auv-driver-macos/overlay", "auv-driver-windows/overlay"]

[dependencies]
auv-driver-common = { version = "0.0.20", path = "../auv-driver-common" }
auv-driver-overlay = { version = "0.0.20", path = "../auv-driver-overlay", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
auv-driver-linux = { version = "0.0.20", path = "../auv-driver-linux" }

[target.'cfg(target_os = "macos")'.dependencies]
auv-driver-macos = { version = "0.0.20", path = "../auv-driver-macos" }

[target.'cfg(target_os = "windows")'.dependencies]
auv-driver-windows = { version = "0.0.20", path = "../auv-driver-windows" }
